#extending from nginx docker image
FROM nginx:latest

WORKDIR /usr/share/nginx/html
# change working directory to root of nginx webhost

COPY index.html index.html

# I don't have to specify EXPOSE or CMD because they're in my FROM