---
- name: Configure docker nginx
  gather_facts: no
  hosts: localhost
  vars:
    docker_image: javierdobles/nginx-cargill
    tag: latest
  tasks:
    - name: Download docker image
      docker_image:
        name: "{{ docker_image }}"
        tag: "{{ tag }}"
        source: pull

    - name: Create nginx container and start it
      docker_container:
       name: nginx-cargill
       image: "{{ docker_image }}"